# Generated by Django 4.1 on 2022-08-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_discussionroom_topic_message_discussionroom_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Region',
        ),
        migrations.RenameField(
            model_name='discussionroom',
            old_name='topic',
            new_name='region',
        ),
    ]
