# Generated by Django 4.1 on 2022-08-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_topic_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussionroom',
            old_name='paticipants',
            new_name='participants',
        ),
    ]
