# Generated by Django 4.1 on 2022-08-22 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_paticipants_discussionroom_participants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscussionRoom',
            new_name='Channel',
        ),
        migrations.RenameModel(
            old_name='Region',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='region',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='channel',
        ),
    ]
