# Generated by Django 4.1 on 2022-09-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_privatechat_privatemessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='degree',
            new_name='Courses',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='hobbies',
            new_name='Major',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='picture',
            new_name='Picture',
        ),
    ]
