# Generated by Django 3.2.15 on 2022-10-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20221004_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Picture',
            field=models.ImageField(default='', null=True, upload_to='..static/images/avatar/'),
        ),
    ]
